### PR TITLE
Dev 0.5

### PR DESCRIPTION
**Pull request by mattlongman**
Merged https://github.com/mattlongman/Hassio-Access-Point/pull/20 from @mrdis into dev-0.5 branch to allow for further testing.

### CODE REVIEW

**Comment by hellresistor** [comment]
hi friend. sometime not here. well today i have retry this version. but seems not spread the signal.

config:
```
ssid: AP-NAME
wpa_passphrase: AP-PASSWORD
channel: "6"
address: 192.168.10.1
netmask: 255.255.255.0
broadcast: 192.168.10.255
interface: wlan0
virtual_interface: ""
isolation: "0"
hide_ssid: "1"
dhcp: "1"
dhcp_start_addr: 192.168.10.10
dhcp_end_addr: 192.168.10.20
allow_mac_addresses: []
deny_mac_addresses:
  - ab:cd:ef:fe:dc:ba
debug: "0"
hostapd_config_override: []
client_internet_access: "1"
client_dns_override:
  - 1.1.1.1
  - 8.8.8.8
dnsmasq_config_override:
  - 1.1.1.1
  - 8.8.8.8

```

log
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Starting Hass.io Access Point Addon
Denied MAC addresses:
ab:cd:ef:fe:dc:ba
Add custom DNS: dhcp-option=6,1.1.1.1,8.8.8.8
# Custom dnsmasq config options:
Add to dnsmasq.conf: 1.1.1.1
Add to dnsmasq.conf: 8.8.8.8
dnsmasq: bad option at line 9 of /dnsmasq.conf
rfkill: Cannot open RFKILL control device
wlan0: interface state UNINITIALIZED->ENABLED
wlan0: AP-ENABLED 
```

what i am missing? o/

**Comment by dingausmwald** [comment]
I believe you use "dnsmasq_config_override" wrong: Delete the entries as your logs imply that something is wrong with your dnsmasq.conf (at line 9). You see what you are doing here?

client_dns_override:
  - 1.1.1.1
  - 8.8.8.8
dnsmasq_config_override:
  - 1.1.1.1
  - 8.8.8.8

**Comment by hellresistor** [comment]
thank you friend. 
Now i have the device detecting the network! well for my proposes will be fine, but i would like (because some future reason) to try use internet on the device, but seems not getting internet.

i have tryied dns 8.8.8.8 1.1.1.1 127.0.0.1 , pihole (dns master)ip  

config:
```
ssid: AP-NAME
wpa_passphrase: AP-PASSWORD
channel: "6"
address: 192.168.10.1
netmask: 255.255.255.0
broadcast: 192.168.10.255
interface: wlan0
hide_ssid: 0
dhcp: "1"
dhcp_start_addr: 192.168.10.10
dhcp_end_addr: 192.168.10.20
allow_mac_addresses: []
deny_mac_addresses: []
debug: "1"
hostapd_config_override: []
client_internet_access: "1"
client_dns_override: []
  - 8.8.8.8
dnsmasq_config_override: []
virtual_interface: ""
isolation: "0"
```

log:
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Starting Hass.io Access Point Addon
# Setup interface:
Add to /etc/network/interfaces: iface wlan0 inet static
Run command: nmcli dev set wlan0 managed no
Run command: ip link set wlan0 down
Add to /etc/network/interfaces: address 192.168.10.1
Add to /etc/network/interfaces: netmask 255.255.255.0
Add to /etc/network/interfaces: broadcast 192.168.10.255
Run command: ip link set wlan0 up
# Setup hostapd:
Add to hostapd.conf: ssid=AP-NAME
Add to hostapd.conf: wpa_passphrase=********
Add to hostapd.conf: channel=6
Add to hostapd.conf: ignore_broadcast_ssid=0
Add to hostapd.conf: macaddr_acl=0
Add to hostapd.conf: interface=wlan0
# DHCP enabled. Setup dnsmasq:
Add to dnsmasq.conf: dhcp-range=192.168.10.10,192.168.10.20,12h
Add to dnsmasq.conf: interface=wlan0
Add DNS: dhcp-option=6,192.168.1.32
## Starting dnsmasq daemon
## Starting hostapd daemon
rfkill: Cannot open RFKILL control device
wlan0: interface state UNINITIALIZED->ENABLED
wlan0: AP-ENABLED 
wlan0: STA 72:da:c5:e3:c8:29 IEEE 802.11: associated
wlan0: AP-STA-CONNECTED 72:da:c5:e3:c8:69
wlan0: STA 72:da:c5:e3:c8:69 RADIUS: starting accounting session 2FBD8358BA34D60E
wlan0: STA 72:da:c5:e3:c8:69 WPA: pairwise key handshake completed (RSN)
wlan0: EAPOL-4WAY-HS-COMPLETED 72:da:c5:e3:c8:69
```

Best regards

**Comment by dingausmwald** [comment]
Should work like this already. But try removing client_dns_override. Remove the "" from client_internet_access: "1"
On my system it looks like this
client_internet_access: 1

But i dont use the dev 0.5 version.

You are sure you have internet over ethernet cable?

In general: Read better! Compare the settings from the readme, symbol by symbol. You are kind of inaccurate. Try yourself some combinations, make notes.
And, dont use this for private help. There is a Discussions section here where you can ask things.
This section is for discussions on pull requests.

**Comment by hellresistor** [comment]
> Should work like this already. But try removing client_dns_override. Remove the "" from client_internet_access: "1" On my system it looks like this client_internet_access: 1
I have i think all possible combinations ^^''

> But i dont use the dev 0.5 version.
I have try both versions. i am using a raspberry pi4 with debian 11 ... should be this a glitch?

> You are sure you have internet over ethernet cable?
Yes, sure..

> In general: Read better! Compare the settings from the readme, symbol by symbol. You are kind of inaccurate. Try yourself some combinations, make notes. And, dont use this for private help. There is a Discussions section here where you can ask things. This section is for discussions on pull requests.
Sorry

**Comment by dingausmwald** [comment]
Sorry man. Could be alot.
How do you make clear your device dont connect to the internet? Best way to test is connect with your smartphone over wifi to the new AP (Raspberry) and try to google.
Maybe you want a connection from your computer to the device behind the raspberry? That would be another story and has nothing to do with internet.

**Comment by ROBOT0-VT** [comment]
Closed due to being stale

**Pull request closed without merging**
